Custom Loot Table:
  Diamond 1:
    Material: DIAMOND
    Spawn Probability: 20 # 1 - 100
    Minimum Quantity: 1 # 0 - 64
    Maximum Quantity: 27 # 0 - 64
  Diamond 2:
    Material: DIAMOND
    Spawn Probability: 45 # 1 - 100
    Minimum Quantity: 1 # 0 - 64
    Maximum Quantity: 64 # 0 - 64
  Obsidian:
    Material: OBSIDIAN
    Spawn Probability: 90 # 1 - 100
    Minimum Quantity: 1 # 0 - 64
    Maximum Quantity: 5 # 0 - 64