Custom Loot Table:
  Diamond 1:
    Material: Diamond
    Spawn Probability: # 1 - 100
    Minimum Amount: 1 # greater than 0
    Maximum Amount: 27 # max 64
  Diamond 2:
    Material: Diamond
    Spawn Probability: # 1 - 100
    Minimum Quantity: 1 # greater than 0
    Maximum Quantity: 27 # max 64